services:
  db:
    image: postgres:16
    container_name: mini-api-db
    environment:
      POSTGRES_DB: miniapihub
      POSTGRES_USER: miniuser
      POSTGRES_PASSWORD: minipass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U miniuser -d miniapihub"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-api-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miniapihub
      SPRING_DATASOURCE_USERNAME: miniuser
      SPRING_DATASOURCE_PASSWORD: minipass
    networks:
      - mini-net

networks:
  mini-net:

volumes:
  postgres_data:
